import cpp from './assets/cpp';
import go from './assets/go';
import css from './assets/css';
import html from './assets/html';
import java from './assets/java';
import javascript from './assets/javascript';
import php from './assets/php';
import python from './assets/python';
import react from './assets/react';